-- MySQL Script generated by MySQL Workbench
-- Sat Jun  4 07:42:52 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema precato
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema precato
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `precato` DEFAULT CHARACTER SET utf8 ;
USE `precato` ;

-- -----------------------------------------------------
-- Table `precato`.`message_flow`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `precato`.`message_flow` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `template_name` VARCHAR(45) NOT NULL,
  `position` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `precato`.`subscriptions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `precato`.`subscriptions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `subscription_date` TIMESTAMP NULL,
  `name` VARCHAR(45) NULL,
  `last_message` INT NULL,
  `active` TINYINT NOT NULL DEFAULT 1,
  `message_flow_id` INT NOT NULL,
  `email` VARCHAR(45) NULL UNIQUE,
  PRIMARY KEY (`id`),
  INDEX `fk_subscription_message_flow_idx` (`message_flow_id` ASC) VISIBLE,
  CONSTRAINT `fk_subscription_message_flow`
    FOREIGN KEY (`message_flow_id`)
    REFERENCES `precato`.`message_flow` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  INDEX `fk_last_message_idx` (`last_message` ASC) VISIBLE,
  CONSTRAINT `fk_last_message`
    FOREIGN KEY (`last_message`)
    REFERENCES `precato`.`messages` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)

-- -----------------------------------------------------
-- Table `precato`.`messages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `precato`.`messages` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `subject` VARCHAR(100) NULL,
  `created_at` TIMESTAMP NOT NULL,
  `message_flow_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `created_at_idx` (`created_at` ASC) VISIBLE,
  INDEX `fk_message_flow_id_idx` (`message_flow_id` ASC) VISIBLE,
  CONSTRAINT `fk_message_flow_id`
    FOREIGN KEY (`message_flow_id`)
    REFERENCES `precato`.`message_flow_id` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
